name: phage-host-prediction
channels:
    - conda-forge
dependencies:
    - python=3.9
    - regex
    - nltk
    - biopython=1.78
    - ete3=3.1.2
    - pandas=1.5.3
    - numpy=1.23
    - scipy
    - scikit-learn=1.0.2
    - imbalanced-learn=0.10.1
    - pyyaml=5.4.1
    - xgboost
    - joblib
    - numba
    - matplotlib
    - jsonnet
    - pip
    - cudatoolkit=11.8
    - pip:
        - bio-embeddings[all]==0.2.1
        - umap-learn[plot]
